import Head from 'next/head'
import Homepage from './homepage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="http://fonts.googleapis.com/css?family=Lato:400,700"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>

      <Homepage></Homepage>
    </div>
  )
}
