import Head from 'next/head'
import Homepage from './homepage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Homepage></Homepage>
    </div>
  )
}
